# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Flowwy EDM
tagline:          'Discovering the world of Dark Electronic Music.'
description:      'Discovering the world of Dark Electronic Music.'
url:              http://flowwy-edm.develic.com
baseurl:          /

author:
  name:           'Andreas Sotnik'
  url:            https://soundcloud.com/flowwy-edm

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
